// Aula - Demonstração de como usar o Selenium
// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

describe('Selecionar produto', function () {
    this.timeout(30000); // Espera até 30s pelo carregamento
    let driver; // Declaração do objeto para o Selenium
    let vars;

    // O que ocorre antes do teste
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build(); // Instancia o driver como ChromeDriver
        vars = {};
        driver.manage().setTimeouts({ implicit: 3000 }); // Define uma espera de até 3s para a seleção de qualquer elemento - Espera até 3s
    });

    // O que ocorre depois do teste
    afterEach(async function () {
        await driver.quit(); // Destrói a instancia do Selenium
    });

    // O teste
    it('Login Positivo', async function () {
        await driver.get('https://www.saucedemo.com/');
        await driver.manage().window().setRect({ width: 1860, height: 942 });
        await driver.findElement(By.id('user-name')).sendKeys('standard_user'); // Preencher o campo usuário
        await driver.findElement(By.id('password')).sendKeys('secret_sauce'); // Preencher o campo senha
        await driver.findElement(By.css('input.submit-button.btn_action')).click(); // Clicar no botão de login
        assert((await driver.findElement(By.css('span.title')).getText()) == 'Products'); // Validar que realmente entrou na página de produtos
    });
});
